spring:
  application:
    name: imaginnovate assesment
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9099